# Generated by Django 3.2.5 on 2021-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='international_code',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
